### ISSUE TITLE
Unable to download Schedule

### ISSUE THREAD

**Issue by carels** [wernerhp/ha.integration.load_shedding#12]
Hi, 

I'm not able to receive any schedules. Sensor state shows no scheduling data:

<img width="923" alt="Screenshot 2022-07-03 at 08 47 32" src="https://user-images.githubusercontent.com/6865403/177028470-c70ea7dd-e491-47f8-b851-9ac36de95e44.png">

```
Error doing job: Task exception was never retrieved
08:50:40 – (ERROR) Load Shedding (custom integration)
Error adding entities for domain sensor with platform load_shedding
08:50:32 – (ERROR) Sensor (custom integration) - message first occurred at 08:50:32 and shows up 2 times
```

More details from the logs:

```
2022-07-03 08:50:32 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform load_shedding
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 810, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
state = self._stringify_state(available)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
if (state := self.state) is None:
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 388, in state
value = self.native_value
File "/config/custom_components/load_shedding/sensor.py", line 172, in native_value
start_time = datetime.fromisoformat(schedule[0].get(ATTR_START_TIME))
IndexError: list index out of range
```

^ This error might be because I have a sensor template that's not able to get the start / end timestamps. I did previously see errors about retrieving the schedule, but after loadshedding I'm not seeing them reappear. 

Loadshedding v0.2.0-alpha

**Comment by wernerhp** [comment]
Did you get schedules in the previous version?  I wouldn't think so.  Schedule data for Durbanville is not available from Eskom.

![Screenshot_20220705-083013](https://user-images.githubusercontent.com/2578772/177264070-0f643dd2-84fa-44eb-80e5-41c15a817edc.png)

First try and find it on https://loadshedding.eskom.co.za/ You can search for another area that has the same schedule as Durbanville.  

Working on filtering out unsupported suburbs and later supporing more providers.

**Comment by carels** [comment]
Thanks Werner,

I've had a dig through the Eskom schedules, there doesn't seem to be anything matching Area 6 in Cpt. (some close, but nothing exact).  I'll keep an eye out for updates on the City of Cape Town issue and check it out once it is ready :)

**Comment by wernerhp** [comment]
I've looked at CPT schedules.  Have something going, but the problem remains getting the correct stage for CPT.  There's no reliable way to get the CPT specific stage.  I guess just getting the Area schedule with Eskom stages is good enough for starters?

**Comment by carels** [comment]
Sounds great! Def better to be over prepared for loadshedding for now :)

**Comment by wernerhp** [comment]
https://github.com/wernerhp/ha.integration.load_shedding/releases/tag/v0.4.0
