### ISSUE TITLE
Error adding entities for domain sensor with platform load_shedding

### ISSUE THREAD

**Issue by grahamwt007** [wernerhp/ha.integration.load_shedding#23]
Logger: homeassistant.components.sensor
Source: custom_components/load_shedding/sensor.py:192
Integration: Sensor (documentation, issues)
First occurred: 7:30:38 AM (4 occurrences)
Last logged: 12:17:42 PM

Error adding entities for domain sensor with platform load_shedding
Error while setting up load_shedding platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 673, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 776, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 388, in state
    value = self.native_value
  File "/config/custom_components/load_shedding/sensor.py", line 192, in native_value
    start_time = datetime.fromisoformat(schedule[0].get(ATTR_START_TIME))
IndexError: list index out of range

**Comment by wernerhp** [comment]
Likely an Eskom data issue, but please try deleting the `.cache` folder in your `config` folder and reload the integration.

**Comment by wernerhp** [comment]
Please try [v1.0.0](https://github.com/wernerhp/ha.integration.load_shedding/releases/tag/v1.0.0)
