### ISSUE TITLE
Unable to reach Provider. See Logs for details.

### ISSUE THREAD

**Issue by RandomSheepZA** [wernerhp/ha.integration.load_shedding#93]
![image](https://github.com/wernerhp/ha.integration.load_shedding/assets/143823490/d34a9771-0199-46ed-9a19-73f3b1e4c968)

Not entirely sure where to grab the logs, new to this. Happy to share if you can advise.

TIA

**Comment by RandomSheepZA** [comment]
This might be what you need:

2024-03-08 19:22:55.732 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-03-08 19:22:55.732 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration load_shedding which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-03-08 19:22:55.732 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-03-08 19:22:55.733 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration weatherflow_forecast which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-03-08 19:22:56.993 WARNING (MainThread) [py.warnings] /usr/local/lib/python3.12/site-packages/telegram/utils/request.py:49: UserWarning: python-telegram-bot is using upstream urllib3. This is allowed but not supported by python-telegram-bot maintainers.
  warnings.warn(

2024-03-08 19:22:58.559 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
2024-03-08 19:23:01.492 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/telegram_bot/polling.py", line 55, in start_polling
    self.updater.start_polling()
  File "/usr/local/lib/python3.12/site-packages/telegram/ext/updater.py", line 285, in start_polling
    self._init_thread(self.dispatcher.start, "dispatcher", ready=dispatcher_ready)
  File "/usr/local/lib/python3.12/site-packages/telegram/ext/updater.py", line 225, in _init_thread
    name=f"Bot:{self.bot.id}:{name}",
                ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/telegram/bot.py", line 117, in decorator
    self.get_me()
  File "/usr/local/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/telegram/bot.py", line 135, in decorator
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/telegram/bot.py", line 392, in get_me
    result = self._post('getMe', timeout=timeout, api_kwargs=api_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/telegram/bot.py", line 245, in _post
    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/telegram/utils/request.py", line 349, in post
    result = self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/telegram/utils/request.py", line 270, in _request_wrapper
    raise Unauthorized(message)
telegram.error.Unauthorized: Unauthorized
2024-03-08 19:28:39.197 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({% if states("sensor.load_shedding_milnerton_14") == "off" %} Starts in {{ timedelta(minutes=state_attr("sensor.load_shedding_area_jhbcitypower3_5_kloofendal", "next_start_time")) }} {% else %} Ends in {{ timedelta(minutes=state_attr("sensor.load_shedding_area_jhbcitypower3_5_kloofendal", "next_end_time")) }} {% endif %}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 573, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2364, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.12/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unsupported type for timedelta minutes component: NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 699, in async_render_to_info
    render_info._result = self.async_render(
                          ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 575, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: TypeError: unsupported type for timedelta minutes component: NoneType
2024-03-08 19:28:39.201 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ (state_attr("sensor.load_shedding_area_jhbcitypower3_5_kloofendal", "next_start_time") | as_datetime | as_local).strftime("%H:%M") }} -  {{ (state_attr("sensor.load_shedding_area_jhbcitypower3_5_kloofendal", "next_end_time") | as_datetime | as_local).strftime("%H:%M") }}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1874, in as_datetime
    timestamp = float(value)
                ^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1879, in as_datetime
    return dt_util.parse_datetime(value, raise_on_error=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/dt.py", line 209, in parse_datetime
    return ciso8601.parse_datetime(dt_str)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument must be str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 573, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2364, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1886, in as_datetime
    raise_no_default("as_datetime", value)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1668, in raise_no_default
    raise ValueError(
ValueError: Template error: as_datetime got invalid input 'None' when rendering template '{{ (state_attr("sensor.load_shedding_area_jhbcitypower3_5_kloofendal", "next_start_time") | as_datetime | as_local).strftime("%H:%M") }} -  {{ (state_attr("sensor.load_shedding_area_jhbcitypower3_5_kloofendal", "next_end_time") | as_datetime | as_local).strftime("%H:%M") }}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 699, in async_render_to_info
    render_info._result = self.async_render(
                          ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 575, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: as_datetime got invalid input 'None' when rendering template '{{ (state_attr("sensor.load_shedding_area_jhbcitypower3_5_kloofendal", "next_start_time") | as_datetime | as_local).strftime("%H:%M") }} -  {{ (state_attr("sensor.load_shedding_area_jhbcitypower3_5_kloofendal", "next_end_time") | as_datetime | as_local).strftime("%H:%M") }}' but no default was specified

**Comment by RandomSheepZA** [comment]
And today, it worked.
So sorted now.

**Comment by wernerhp** [comment]
You may want to update your Status Alert card.  
https://github.com/wernerhp/ha.integration.load_shedding/releases/tag/v1.3.2
